name: ahmed_ragab
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.1.0
  shared_preferences: ^2.0.7
  flutter_slidable: ^0.6.0
  flutter_screenutil: ^5.0.0+2
  image_picker: ^0.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # assets:
  #   - assets/

  fonts:
    - family: exo2
      fonts:
        - asset: fonts/exo2/Exo2-Black.ttf
          weight: 900
        - asset: fonts/exo2/Exo2-BlackItalic.ttf
          style: italic
          weight: 900

        - asset: fonts/exo2/Exo2-ExtraBold.ttf
          weight: 800
        - asset: fonts/exo2/Exo2-ExtraBoldItalic.ttf
          style: italic
          weight: 800

        - asset: fonts/exo2/Exo2-Bold.ttf
          weight: 700
        - asset: fonts/exo2/Exo2-BoldItalic.ttf
          style: italic
          weight: 700

        - asset: fonts/exo2/Exo2-SemiBold.ttf
          weight: 600
        - asset: fonts/exo2/Exo2-SemiBoldItalic.ttf
          style: italic
          weight: 600

        - asset: fonts/exo2/Exo2-Medium.ttf
          weight: 500
        - asset: fonts/exo2/Exo2-MediumItalic.ttf
          style: italic
          weight: 500

        - asset: fonts/exo2/Exo2-Regular.ttf
          weight: 400
        - asset: fonts/exo2/Exo2-Italic.ttf
          style: italic
          weight: 400

        - asset: fonts/exo2/Exo2-Light.ttf
          weight: 300
        - asset: fonts/exo2/Exo2-LightItalic.ttf
          style: italic
          weight: 300

        - asset: fonts/exo2/Exo2-ExtraLight.ttf
          weight: 200
        - asset: fonts/exo2/Exo2-ExtraLightItalic.ttf
          style: italic
          weight: 200

        - asset: fonts/exo2/Exo2-Thin.ttf
          weight: 100
        - asset: fonts/exo2/Exo2-ThinItalic.ttf
          style: italic
          weight: 100
